-- 创建用户表
CREATE TABLE users
(
    user_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   NVARCHAR2(255) NOT NULL,
    email      NVARCHAR2(255) NOT NULL,
    password   NVARCHAR2(255) NOT NULL,
    role       NVARCHAR2(50) DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    avatar_url NVARCHAR2(255),
    metadata   CLOB,
    last_login TIMESTAMP,
    status     NVARCHAR2(50) DEFAULT 'inactive' CHECK (status IN ('active', 'inactive', 'deleted', 'banned', 'suspended')),
    created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- 创建站点表
CREATE TABLE sites
(
    site_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER         NOT NULL,
    site_name      NVARCHAR2(255) NOT NULL,
    site_url       NVARCHAR2(255) NOT NULL,
    site_desc      CLOB,
    site_image_url NVARCHAR2(255),
    site_config    CLOB,
    site_status    NVARCHAR2(50) DEFAULT 'private' CHECK (site_status IN ('public', 'private')),
    site_ext       CLOB,
    status         NVARCHAR2(50) DEFAULT 'inactive' CHECK (status IN ('active', 'inactive', 'deleted')),
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 创建Tag表
CREATE TABLE tags
(
    tag_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER         NOT NULL,
    tag_name      NVARCHAR2(255) NOT NULL,
    tag_code      CLOB           NOT NULL,
    tag_type      NVARCHAR2(50)  NOT NULL CHECK (tag_type IN ('html', 'css', 'js')),
    tag_status    NVARCHAR2(50) DEFAULT 'private' CHECK (tag_status IN ('public', 'private')),
    tag_desc      CLOB,
    tag_image_url NVARCHAR2(255),
    tag_config    CLOB,
    tag_ext       CLOB,
    status        NVARCHAR2(50) DEFAULT 'inactive' CHECK (status IN ('active', 'inactive', 'deleted')),
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_tag FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 创建项目表
CREATE TABLE projects
(
    project_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER         NOT NULL,
    project_name      NVARCHAR2(255) NOT NULL,
    project_desc      CLOB,
    project_image_url NVARCHAR2(255),
    project_config    CLOB,
    project_ext       CLOB,
    project_status    NVARCHAR2(50) DEFAULT 'private' CHECK (project_status IN ('public', 'private')),
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_project FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- 创建访问记录表
CREATE TABLE site_access
(
    access_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_data CLOB,
    site_id     NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_site_access FOREIGN KEY (site_id) REFERENCES sites (site_id)
);

-- 创建访问记录表
CREATE TABLE tag_access
(
    access_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_data CLOB,
    tag_id      NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tag_access FOREIGN KEY (tag_id) REFERENCES tags (tag_id)
);

-- 创建配置表
CREATE TABLE config
(
    k NVARCHAR2(255) PRIMARY KEY,
    v CLOB
);